language: node_js
node_js:
  - "10"

services:
  - docker

before_script:
  - docker run -d --hostname rabbitmq.service --name rabbitmq.service -v /rabbitmq:/var/lib/rabbitmq -v /root:/root -p 5672:5672 -p 15672:15672 -p 15674:15674 -p 15670:15670 -p 61613:61613 quay.io/kreatio/rabbitmq:3.6.8-official-alpine-with-webstomp
  - sleep 10
  - docker exec rabbitmq.service rabbitmqctl status
  - npm run build

script:
  - npm run test && npm run karma
